config/routes.rb
Rails.application.routes.draw do

  root 'homepages#index'

  resources :foods, :areas

end

app/models/area.rb
class Area < ActiveRecord::Base
  has_many :foods
end

app/models/food.rb
class Food < ActiveRecord::Base
  has_many :ordered_foods
  belongs_to :area
end

app/models/order.rb
class Order < ActiveRecord::Base
  belongs_to :user
  has_many :ordered_foods
end

app/models/ordered_food.rb
class OrderedFood < ActiveRecord::Base
  belongs_to :order
  belongs_to :food
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  has_many :orders
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/areas_controller.rb
class AreasController < ApplicationController

  def index
    @area = Area.all
  end

  def show
    set_area
  end

  def new
  end

  def create
    @area = Area.new(area_params)
    if @area.save!
      redirect_to areas_path
    else
      render :new
    end
  end

  def edit
    set_area
  end

  def update
    set_area
    if @area.update(area_params)
      redirect_to areas_path
    else
      render :edit
    end
  end

  def destroy
    set_area
    @area.destroy
    redirect_to areas_path
  end

  private

  def area_params
    params.require(:area).permit(:name, :address, :city, :postcode, :state, :image)
  end

  def set_area
    @area = Area.find(params[:id])
  end

end

app/controllers/foods_controller.rb
class FoodsController < ApplicationController

  def index
    @food = Food.all
  end

  def new
  end

  def create
    @food = Food.new(food_params)
    if @food.save!
      redirect_to foods_path
      flash[:notice] = "Food Successfully uploaded"
    else
      render :new
      flash[:warning] = "Food not created!"
    end
  end

  def show
    set_food
  end

  def edit
    set_food
  end

  def update
    set_food
    if @food.update(food_params)
      redirect_to foods_path
    else
      render :edit
    end
  end

  def destroy
    set_food
    @food.destroy
    redirect_to foods_path
  end


  private

  def food_params
    params.require(:food).permit(:title, :description, :date, :price, :area_id, images: [])
  end

  def set_food
    @food = Food.find(params[:id])
  end

end

app/controllers/homepages_controller.rb
class HomepagesController < ApplicationController

  def index
    @food = Food.all
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/areas_helper.rb
module AreasHelper
end

app/helpers/foods_helper.rb
module FoodsHelper
end

app/views/areas/edit.html.erb
<h1>This is area page</h1>

<%= form_for :area, url: area_path, method: :put do |t| %>
  
<div>
  <label>Name:</label>  
  <%= t.text_field :name %>
</div>

<div>
  <label>Address:</label>
  <%= t.text_field :address %>
</div>

<div>
  <label>City:</label>
  <%= t.text_field :city %>
</div>

<div>
  <label>Postcode:</label>
  <%= t.text_field :postcode %>
</div>

<div>
  <label>State:</label>
  <%= t.text_field :state %>
</div>

<div>
  <label>Image:</label>
  <%= t.file_field :image %>
</div>

<div>
  <%= t.submit "Edit Area!" %>
</div>  

<% end %>

app/views/areas/index.html.erb
<h1>This is area index</h1>

<% @area.each_with_index do | t, index| %>
  <div>
    <%= link_to t do %>
    <%= "#{index+1}. #{t.name}" %>
    <% end %>
  </div>
<% end %>

<div>
  <%= link_to "Create new area!", new_area_path %>
</div>

app/views/areas/new.html.erb
<h1>This is area page</h1>

<%= form_for :area, url: areas_path do |t| %>
  
<div>
  <label>Name:</label>  
  <%= t.text_field :name %>
</div>

<div>
  <label>Address:</label>
  <%= t.text_field :address %>
</div>

<div>
  <label>City:</label>
  <%= t.text_field :city %>
</div>

<div>
  <label>Postcode:</label>
  <%= t.text_field :postcode %>
</div>

<div>
  <label>State:</label>
  <%= t.text_field :state %>
</div>

<div>
  <label>Image:</label>
  <%= t.file_field :image %>
</div>

<div>
  <%= t.submit "Create Area!" %>
</div>  

<% end %>

app/views/areas/show.html.erb
<div>
  <h1><%= @area.name %></h1>
</div>

<div>
  <%= @area.address %>
</div>

<div>
  <%= @area.city %>
</div>

<div>
  <%= @area.postcode %>
</div>

<div>
  <%= @area.state %>
</div>

<div class="btn btn-warning">
<%= link_to "Delete this post", area_path(@area), method: :delete %></div>

<div class="btn btn-warning">
<%= link_to "Edit this post", edit_area_path %></div>

<div class="btn btn-warning">
<%= link_to "Back", areas_path %>
</div>

app/views/foods/edit.html.erb
<h1>Edit your Food here</h1>

<%= form_for :food, url: food_path, method: :put do |t| %>
  
<div>
  <label>Title:</label>  
  <%= t.text_field :title %>
</div>

<div>
  <label>Description:</label>
  <%= t.text_field :description %>
</div>

<div>
  <label>Date</label>
  <%= t.date_field :date %>
</div>

<div>
  <label>Price:</label>
  <%= t.text_field :price %>
</div>

<div>
  <label>Area id:</label>
  <%= t.text_field :area_id %>
</div>

<div>
  <label>Image:</label>
  <%= t.file_field :images %>
</div>

<div>
  <%= t.submit "Edit Food!" %>
</div>  

<% end %>

app/views/foods/index.html.erb
<h1>This is the food index</h1>

<% @food.each_with_index do | t, index| %>
  <div>
  <%= link_to t do %>
  <% = "#{index+1}. #{t.title}" %>
  </div>
  <% end %>

<% end %>

<div>
  <%= link_to "CreateNewFood", new_food_path %>
</div

app/views/foods/new.html.erb
<h1>This is create food page</h1>

<%= form_for :food, url: foods_path do |t| %>
  
<div>
  <label>Title:</label>  
  <%= t.text_field :title %>
</div>

<div>
  <label>Description:</label>
  <%= t.text_field :description %>
</div>

<div>
  <label>Date</label>
  <%= t.date_field :date %>
</div>

<div>
  <label>Price:</label>
  <%= t.text_field :price %>
</div>

<div>
  <label>Area id:</label>
  <%= t.text_field :area_id %>
</div>

<div>
  <label>Image:</label>
  <%= t.file_field :images %>
</div>

<div>
  <%= t.submit "Create Food!" %>
</div>  

<% end %>

app/views/foods/show.html.erb
<div>
  <h1><%= @food.title %></h1>
</div>

<div>
  <%= @food.description %>
</div>

<div>
  <%= @food.date %>
</div>

<div>
  <%= @food.price %>
</div>

<div>
  <%= @food.area_id %>
</div>

<div class="btn btn-warning">
<%= link_to "Delete this post", food_path(@food), method: :delete %></div>

<div class="btn btn-warning">
<%= link_to "Edit this post", edit_food_path %></div>

<div class="btn btn-warning">
<%= link_to "Back", foods_path %>
</div>

app/views/homepages/index.html.erb
<h1>Welcome this is our index page</h1>

<% @food.each_with_index do | t, index| %>
  <div>
    <%= link_to t do %>
    <%= "#{index+1}. #{t.title}" %>
    <% end %>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Defruitkitchen</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <% if flash[:notice] %>
    <div class="notice"><%= flash[:notice] %></div>
  <% end %>
<%= yield %>

</body>
</html>